package com.git.onedayrex.nettyaction.nettyguide81.dto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OrderInfoResp.proto

public final class OrderInfoRespOuterClass {
  private OrderInfoRespOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OrderInfoRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OrderInfoResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 reqId = 1;</code>
     */
    int getReqId();

    /**
     * <code>string orderNo = 2;</code>
     */
    String getOrderNo();
    /**
     * <code>string orderNo = 2;</code>
     */
    com.google.protobuf.ByteString
        getOrderNoBytes();

    /**
     * <code>string goodName = 3;</code>
     */
    String getGoodName();
    /**
     * <code>string goodName = 3;</code>
     */
    com.google.protobuf.ByteString
        getGoodNameBytes();
  }
  /**
   * Protobuf type {@code OrderInfoResp}
   */
  public  static final class OrderInfoResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:OrderInfoResp)
      OrderInfoRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OrderInfoResp.newBuilder() to construct.
    private OrderInfoResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OrderInfoResp() {
      reqId_ = 0;
      orderNo_ = "";
      goodName_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OrderInfoResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              reqId_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              orderNo_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              goodName_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return OrderInfoRespOuterClass.internal_static_OrderInfoResp_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return OrderInfoRespOuterClass.internal_static_OrderInfoResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              OrderInfoResp.class, Builder.class);
    }

    public static final int REQID_FIELD_NUMBER = 1;
    private int reqId_;
    /**
     * <code>int32 reqId = 1;</code>
     */
    public int getReqId() {
      return reqId_;
    }

    public static final int ORDERNO_FIELD_NUMBER = 2;
    private volatile Object orderNo_;
    /**
     * <code>string orderNo = 2;</code>
     */
    public String getOrderNo() {
      Object ref = orderNo_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        orderNo_ = s;
        return s;
      }
    }
    /**
     * <code>string orderNo = 2;</code>
     */
    public com.google.protobuf.ByteString
        getOrderNoBytes() {
      Object ref = orderNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        orderNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GOODNAME_FIELD_NUMBER = 3;
    private volatile Object goodName_;
    /**
     * <code>string goodName = 3;</code>
     */
    public String getGoodName() {
      Object ref = goodName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        goodName_ = s;
        return s;
      }
    }
    /**
     * <code>string goodName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getGoodNameBytes() {
      Object ref = goodName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        goodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (reqId_ != 0) {
        output.writeInt32(1, reqId_);
      }
      if (!getOrderNoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, orderNo_);
      }
      if (!getGoodNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, goodName_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (reqId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, reqId_);
      }
      if (!getOrderNoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, orderNo_);
      }
      if (!getGoodNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, goodName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof OrderInfoResp)) {
        return super.equals(obj);
      }
      OrderInfoResp other = (OrderInfoResp) obj;

      boolean result = true;
      result = result && (getReqId()
          == other.getReqId());
      result = result && getOrderNo()
          .equals(other.getOrderNo());
      result = result && getGoodName()
          .equals(other.getGoodName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQID_FIELD_NUMBER;
      hash = (53 * hash) + getReqId();
      hash = (37 * hash) + ORDERNO_FIELD_NUMBER;
      hash = (53 * hash) + getOrderNo().hashCode();
      hash = (37 * hash) + GOODNAME_FIELD_NUMBER;
      hash = (53 * hash) + getGoodName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static OrderInfoResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OrderInfoResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OrderInfoResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OrderInfoResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OrderInfoResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OrderInfoResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OrderInfoResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OrderInfoResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static OrderInfoResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static OrderInfoResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static OrderInfoResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static OrderInfoResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(OrderInfoResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OrderInfoResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OrderInfoResp)
        OrderInfoRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return OrderInfoRespOuterClass.internal_static_OrderInfoResp_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return OrderInfoRespOuterClass.internal_static_OrderInfoResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                OrderInfoResp.class, Builder.class);
      }

      // Construct using OrderInfoRespOuterClass.OrderInfoResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        reqId_ = 0;

        orderNo_ = "";

        goodName_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return OrderInfoRespOuterClass.internal_static_OrderInfoResp_descriptor;
      }

      @Override
      public OrderInfoResp getDefaultInstanceForType() {
        return OrderInfoResp.getDefaultInstance();
      }

      @Override
      public OrderInfoResp build() {
        OrderInfoResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public OrderInfoResp buildPartial() {
        OrderInfoResp result = new OrderInfoResp(this);
        result.reqId_ = reqId_;
        result.orderNo_ = orderNo_;
        result.goodName_ = goodName_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof OrderInfoResp) {
          return mergeFrom((OrderInfoResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(OrderInfoResp other) {
        if (other == OrderInfoResp.getDefaultInstance()) return this;
        if (other.getReqId() != 0) {
          setReqId(other.getReqId());
        }
        if (!other.getOrderNo().isEmpty()) {
          orderNo_ = other.orderNo_;
          onChanged();
        }
        if (!other.getGoodName().isEmpty()) {
          goodName_ = other.goodName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        OrderInfoResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (OrderInfoResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int reqId_ ;
      /**
       * <code>int32 reqId = 1;</code>
       */
      public int getReqId() {
        return reqId_;
      }
      /**
       * <code>int32 reqId = 1;</code>
       */
      public Builder setReqId(int value) {
        
        reqId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 reqId = 1;</code>
       */
      public Builder clearReqId() {
        
        reqId_ = 0;
        onChanged();
        return this;
      }

      private Object orderNo_ = "";
      /**
       * <code>string orderNo = 2;</code>
       */
      public String getOrderNo() {
        Object ref = orderNo_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          orderNo_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string orderNo = 2;</code>
       */
      public com.google.protobuf.ByteString
          getOrderNoBytes() {
        Object ref = orderNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          orderNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string orderNo = 2;</code>
       */
      public Builder setOrderNo(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        orderNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string orderNo = 2;</code>
       */
      public Builder clearOrderNo() {
        
        orderNo_ = getDefaultInstance().getOrderNo();
        onChanged();
        return this;
      }
      /**
       * <code>string orderNo = 2;</code>
       */
      public Builder setOrderNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        orderNo_ = value;
        onChanged();
        return this;
      }

      private Object goodName_ = "";
      /**
       * <code>string goodName = 3;</code>
       */
      public String getGoodName() {
        Object ref = goodName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          goodName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string goodName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getGoodNameBytes() {
        Object ref = goodName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          goodName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string goodName = 3;</code>
       */
      public Builder setGoodName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        goodName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string goodName = 3;</code>
       */
      public Builder clearGoodName() {
        
        goodName_ = getDefaultInstance().getGoodName();
        onChanged();
        return this;
      }
      /**
       * <code>string goodName = 3;</code>
       */
      public Builder setGoodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        goodName_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:OrderInfoResp)
    }

    // @@protoc_insertion_point(class_scope:OrderInfoResp)
    private static final OrderInfoResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new OrderInfoResp();
    }

    public static OrderInfoResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OrderInfoResp>
        PARSER = new com.google.protobuf.AbstractParser<OrderInfoResp>() {
      @Override
      public OrderInfoResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OrderInfoResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OrderInfoResp> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<OrderInfoResp> getParserForType() {
      return PARSER;
    }

    @Override
    public OrderInfoResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderInfoResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderInfoResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023OrderInfoResp.proto\"A\n\rOrderInfoResp\022\r" +
      "\n\005reqId\030\001 \001(\005\022\017\n\007orderNo\030\002 \001(\t\022\020\n\010goodNa" +
      "me\030\003 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_OrderInfoResp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_OrderInfoResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderInfoResp_descriptor,
        new String[] { "ReqId", "OrderNo", "GoodName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
